[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview pane"

[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered image"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered image"

[[mgr.prepend_keymap]]
on = [ "g", "v" ]
run = '''
shell 'mpv --vo=tct --vf=fps=10,scale=160:-2 --no-audio --osd-level=0 --msg-level=all=no "$1"' --interactive --block
'''
desc = "Terminal video preview (mpv tct)"

[[mgr.prepend_keymap]]
on = [ "g", "c" ]
run = "plugin vcs-files"
desc = "Show Git file changes"
