model = "gpt-5.4"
model_reasoning_effort = "xhigh"
personality = "pragmatic"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.2-codex" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

[features]
multi_agent = true

[projects."/home/junf/Mecka/hands"]
trust_level = "trusted"

[projects."/home/junf/Mecka/WES_Detector"]
trust_level = "trusted"

[projects."/home/junf/Mecka/datasets/umi_v2m"]
trust_level = "trusted"

[projects."/home/junf/Mecka/util_code/ml_data_ops"]
trust_level = "trusted"

[projects."/home/junf/Mecka/datasets/umi_v2m/train"]
trust_level = "trusted"

[projects."/home/junf/Mecka/sam3-engine"]
trust_level = "trusted"

[projects."/home/junf/Documents"]
trust_level = "trusted"

[projects."/home/junf/Mecka/ml_data_ops"]
trust_level = "trusted"

[projects."/home/junf/Mecka/hamer"]
trust_level = "trusted"

[projects."/home/junf/Projects/seaice/sea-ice-ssl"]
trust_level = "trusted"

[projects."/home/junf/Mecka/haptic"]
trust_level = "trusted"

[projects."/home/junf/Mecka/ultralytics"]
trust_level = "trusted"

[projects."/home/junf/Mecka/hands_dataset_exp/dataset_viz"]
trust_level = "trusted"

[projects."/home/junf/Mecka/rf-detr"]
trust_level = "trusted"

[projects."/home/junf"]
trust_level = "trusted"

[projects."/home/junf/Mecka/hands_dataset_exp"]
trust_level = "trusted"

[projects."/home/junf/Mecka/eval_benchmark"]
trust_level = "trusted"

